name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'worker/**'
      - 'wrangler.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain'
      - .github/workflows/deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare with wrangler
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            wrangler whoami
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
            source $HOME/.cargo/env
            rustc --version
            echo "Run before wrangler publish"
