name: Prettier Format

on:
  pull_request:
    paths:
      - 'worker/**'
      - '.github/workflows/prettier-format.yml'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: prettier
        uses: creyD/prettier_action@v3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prettier_options: --write worker/*.{json,js}
          commit_message: "format: prettier"
